### ISSUE TITLE
background_location: ^0.9.0 not available in pub.dev

### ISSUE THREAD

**Issue by serraojoao** [Almoullim/background_location#166]
Hi, Following the repo instructions it seems version 0.9.0 is available but still not in pub.dev? is it going to be published there in the meantime? 

thanks

**Comment by santhoshrao519** [comment]
I'm getting **Execution failed for task ':fl_location:compileReleaseKotlin'.** when i'm using following: Please help

background_location:
    git:
      url: https://github.com/Almoullim/background_location
      ref: v0.9.0

**Comment by Emanuelguantay** [comment]
This works for my
```
background_location:
    git:
      url: https://github.com/Almoullim/background_location
      ref: master
```
