### ISSUE TITLE
Customize icon, text and optional action button.

### ISSUE THREAD

**Issue by tomk9** [Almoullim/background_location#6]
The plugin works fine but there is no icon when I run example project.
![image](https://user-images.githubusercontent.com/15803067/64908856-50af8800-d705-11e9-8c27-36724e500616.png)
Could you add some customization options for the icon, icon color, text and make "Stop location service" action optional?

**Comment by 0xecute** [comment]
Any updates?

**Comment by 0xecute** [comment]
Hello.
If you are interested, I did the required modifications.
I had to fix the context because it was not working well with others plugins.
What I did is remove the notification completely.
I manage the notification directly in flutter with the plugin local_notifications
https://github.com/noinskit/flutter_local_notifications/ (Branch actions!)


Fork: https://github.com/0xecute/background_location

So what my pubspec.yaml looks like:
```
flutter_local_notifications:
    git:
      url: https://github.com/noinskit/flutter_local_notifications
      ref: actions
  background_location:
    git:
      url: https://github.com/0xecute/background_location
```
